version: '3.8'
services:
  mysql-products-db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_products_volume:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_products_volume:
    driver: local
